services:
  app:
    build:
      context: .
    container_name: ftf_clockify_be
    ports:
      - "${HOST_BACKEND_PORT}:${APP_INTERNAL_PORT}"
    environment:
#      DB
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}

#      BE
      - APP_INTERNAL_PORT=${APP_INTERNAL_PORT}
      - CLOCKIFY_API_KEY=${CLOCKIFY_API_KEY}
      - WORKSPACE_ID=${WORKSPACE_ID}
      - MAEVLAVA_ID=${MAEVLAVA_ID}
      - DEANDRA_ID=${DEANDRA_ID}
    depends_on:
      - postgres_db
    restart: unless-stopped
    networks:
      - backend_dev_network


  postgres_db:
    image: postgres:16
    container_name: ftf_clockify_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - backend_dev_network
    restart: unless-stopped

volumes:
  postgres_dev_data:

networks:
  backend_dev_network:
    driver: bridge