-- +goose Up
CREATE TABLE users(
    id TEXT UNIQUE PRIMARY KEY,
    name TEXT NOT NULL ,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTs users;