// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUsers(ctx context.Context) error
	GetUser(ctx context.Context, name string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
